name: Continuous Integration

on:
  pull_request:
    paths:
      - "**/*.nix"
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
    paths:
      - "**/*.nix"
  workflow_dispatch:

jobs:
  check-code-style:
    name: Check Code Style
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checout Repository
        uses: actions/chekcout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      
      - name: Install nixfmt-rfc-style Package
        run: nix-shell -p nixfmt-rfc-style

      - name: Run nixfmt
        run: nixfmt --check **/*.nix
